/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.heeralshah;

import java.util.List;
import com.aaroncoplan.todoist.helpers.*;
import com.aaroncoplan.todoist.model.*;
import com.aaroncoplan.todoist.Todoist;
import com.aaroncoplan.todoist.TodoistException;
import com.aaroncoplan.todoist.JsonAdapters;

public class GCalTodoistSync{
   
    public static void main(String[] args) throws TodoistException {

        System.out.println("Welcome to my Todoist app");

        Todoist td = new Todoist("05100232bfecbeda0eb587d54e4781bba14350d4");
        td.createNewLabel("newProj");

        List<Project> projects = td.getAllProjects();
        for(Project p : projects) {
            System.out.println(p);
        }
    }
}
