/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.heeralshah;

import org.junit.Test;
import static org.junit.Assert.*;

public class GCalTodoistSyncTest {
    /** 
    @Test public void appHasAGreeting() {
        GCalTodoistSync classUnderTest = new GCalTodoistSync();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    */
}
